apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "enc-app.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.global.environment }}
  KUBERNETES_NAMESPACE: {{ .Release.Namespace }}
