{{- if eq (include "enc-app.shouldDeployRedis" .) "true" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.redis.name }}
  ports:
  - port: {{ .Values.redis.service.port }}
    targetPort: {{ .Values.redis.service.targetPort }}
{{- end }}